INSERT INTO users(email, name, password, roles) VALUES 
('holita@gmail.com', 'admin1', '$2a$12$k8J.LRiyIVY9cWiVXWG3xOrDrxCZyNxppjQS99Ew5BRSo8QKAjLze', 'ROLE_ADMIN'),
('hola@gmail.com', 'player1', '$2a$12$jExPzKwt6E656bpZ0taMQ.w9jsteUbbDZ9wOLqTeIXvRLy4SNIfc.', 'ROLE_USER'),
('test2@test.com', 'player2', '$2a$10$Gsic7B3Si21dACLSoIupy.QdYyDxAABc8PZaE2KIZrU77h7Zhhwxq', 'ROLE_USER'),
('test3@test.com', 'player3', '$2a$10$Gsic7B3Si21dACLSoIupy.QdYyDxAABc8PZaE2KIZrU77h7Zhhwxq', 'ROLE_USER'),
('test4@test.com', 'player4', '$2a$10$Gsic7B3Si21dACLSoIupy.QdYyDxAABc8PZaE2KIZrU77h7Zhhwxq', 'ROLE_USER'),
('test5@test.com', 'player5', '$2a$10$Gsic7B3Si21dACLSoIupy.QdYyDxAABc8PZaE2KIZrU77h7Zhhwxq', 'ROLE_USER');

INSERT INTO players(points, user_id, is_host, is_in_game) VALUES
(0, 2, true, true),
(0, 3, false, false),
(0, 4, false, false),
(0, 5, false, false),
(0, 6, false, false);

INSERT INTO cards(name, description, card_value, type, category, is_treasure, is_protected, is_destroyed, is_chosen, is_revealed, image) VALUES 
('Davy Jones',
'At the start of your turn, you may discard a card to destroy a card. At the end of your turn, draw a card.',
'Solo', 0, 0, false, false, false, false, false, '/resources/static/images/cards/DavyJones.png'),
('Robot Pirate',
'1) Play the rightmost card of the display for its ability. 2) Play the top card at the deck as a treasure. 3) Refill the display from the left.',
'Solo', 0, 0, false, false, false, false, false, '/resources/static/images/cards/RobotPirate.png'),
('Anne Bonny',
'Draw 3 cards. Everyone else draws 1 card.',
'Joker', 0, 0, false, false, false, false, false, '/resources/static/images/cards/AnneBonny.png'),
('Henry Morgan',
'Draw 5 cards. Add 1 to your hand and put the others back in any order.',
'Joker', 0, 0, false, false, false, false, false, '/resources/static/images/cards/HenryMorgan.png'),
('Long John Silver',
'Swap hands with an opponent.',
'Joker', 0, 0, false, false, false, false, false, '/resources/static/images/cards/LongJohnSilver.png'),
('Madame Ching',
'Play 1 card as a permanent and 1 card as a treasure.',
'Joker', 0, 0, false, false, false, false, false, '/resources/static/images/cards/MadameChing.png'),
('Stowaway',
'Play this in front of another player. Their lowest-valued treasure has no value.',
'Joker', 0, 0, false, false, false, false, false, '/resources/static/images/cards/Stowaway.png'),
('Maelstrom',
'Destroy all treasures.',
'A', 0, 3, false, false, false, false, false, '/resources/static/images/cards/Maelstrom.png'),
('Mutiny',
'Choose a number. Destroy all treasures of that value or lower.',
'A', 0, 1, false, false, false, false, false, '/resources/static/images/cards/Mutiny.png'),
('Shiver Me Timbers',
'Everyone discards all odd-numbered cards and destroys all even-numbered cards.',
'A', 0, 2, false, false, false, false, false, '/resources/static/images/cards/ShiverMeTimbers.png'),
('Lifeboat',
'You may destroy this card instead of destroying or discarding other cards.',
'1', 1, 1, true, false, false, false, false, '/resources/static/images/cards/Lifeboat.png'),
('Jolly Roger',
'At the start of your turn, draw a card. If it is a treasure, return it.',
'1', 1, 2, true, false, false, false, false, '/resources/static/images/cards/JollyRoger.png'),
('Ships Wheel',
'Whenever an opponent draws a card as their action, draw a card.',
'1', 1, 3, true, false, false, false, false, '/resources/static/images/cards/ShipsWheel.png'),
('Cutlass',
'Destroy a permanent card. Draw a card.',
'2', 0, 1, true, false, false, false, false, '/resources/static/images/cards/CutlassEyepatch.png'),
('Cutlass',
'Destroy a permanent card. Draw a card.',
'2', 0, 2, true, false, false, false, false, '/resources/static/images/cards/CutlassSkull.png'),
('Cutlass',
'Destroy a permanent card. Draw a card.',
'2', 0, 3, true, false, false, false, false, '/resources/static/images/cards/CutlassHook.png'),
('Monkey',
'Choose a card from the discard pile and add it to your hand.',
'3', 0, 1, true, false, false, false, false, '/resources/static/images/cards/MonkeyEyepatch.png'),
('Monkey',
'Choose a card from the discard pile and add it to your hand.',
'3', 0, 2, true, false, false, false, false, '/resources/static/images/cards/MonkeySkull.png'),
('Monkey',
'Choose a card from the discard pile and add it to your hand.',
'3', 0, 3, true, false, false, false, false, '/resources/static/images/cards/MonkeyHook.png'),
('Cannon',
'One opponent discards 2 cards.',
'4', 0, 1, true, false, false, false, false, '/resources/static/images/cards/CannonEyepatch.png'),
('Cannon',
'One opponent discards 2 cards.',
'4', 0, 2, true, false, false, false, false, '/resources/static/images/cards/CannonSkull.png'),
('Cannon',
'One opponent discards 2 cards.',
'4', 0, 3, true, false, false, false, false, '/resources/static/images/cards/CannonHook.png'),
('Treasure Map',
'Draw 2 cards.',
'5', 0, 1, true, false, false, false, false, '/resources/static/images/cards/TreasureMapEyepatch.png'),
('Treasure Map',
'Draw 2 cards.',
'5', 0, 2, true, false, false, false, false, '/resources/static/images/cards/TreasureMapSkull.png'),
('Treasure Map',
'Draw 2 cards.',
'5', 0, 3, true, false, false, false, false, '/resources/static/images/cards/TreasureMapHook.png'),
('Kraken',
'Destroy all permanents.',
'6', 0, 1, true, false, false, false, false, '/resources/static/images/cards/KrakenEyepatch.png'),
('Kraken',
'Destroy all permanents.',
'6', 0, 2, true, false, false, false, false, '/resources/static/images/cards/KrakenSkull.png'),
('Kraken',
'Destroy all permanents.',
'6', 0, 3, true, false, false, false, false, '/resources/static/images/cards/KrakenHook.png'),
('Skeleton Key',
'Draw a card. Play a card.',
'7', 0, 1, true, false, false, false, false, '/resources/static/images/cards/SkeletonKeyEyepatch.png'),
('Skeleton Key',
'Draw a card. Play a card.',
'7', 0, 2, true, false, false, false, false, '/resources/static/images/cards/SkeletonKeySkull.png'),
('Skeleton Key',
'Draw a card. Play a card.',
'7', 0, 3, true, false, false, false, false, '/resources/static/images/cards/SkeletonKeyHook.png'),
('Spyglass',
'Opponents play with their hands revealed.',
'8', 1, 1, true, false, false, false, false, '/resources/static/images/cards/SpyglassEyepatch.png'),
('Spyglass',
'Opponents play with their hands revealed.',
'8', 1, 2, true, false, false, false, false, '/resources/static/images/cards/SpyglassSkull.png'),
('Spyglass',
'Opponents play with their hands revealed.',
'8', 1, 3, true, false, false, false, false, '/resources/static/images/cards/SpyglassHook.png'),
('Pirate Code',
'Place this on top of a treasure; it is now protected. It cannot be destroyed or stolen.',
'9', 1, 1, true, false, false, false, false, '/resources/static/images/cards/PirateCodeEyepatch.png'),
('Pirate Code',
'Place this on top of a treasure; it is now protected. It cannot be destroyed or stolen.',
'9', 1, 2, true, false, false, false, false, '/resources/static/images/cards/PirateCodeSkull.png'),
('Pirate Code',
'Place this on top of a treasure; it is now protected. It cannot be destroyed or stolen.',
'9', 1, 3, true, false, false, false, false, '/resources/static/images/cards/PirateCodeHook.png'),
('Treasure Chest',
'',
'10', 0, 1, true, false, false, false, false, '/resources/static/images/cards/TreasureChestEyepatch.png'),
('Treasure Chest',
'',
'10', 0, 2, true, false, false, false, false, '/resources/static/images/cards/TreasureChestSkull.png'),
('Treasure Chest',
'',
'10', 0, 3, true, false, false, false, false, '/resources/static/images/cards/TreasureChestHook.png'),
('Lookout',
'Steal a treasure and move it in front of you.',
'J', 0, 1, false, false, false, false, false, '/resources/static/images/cards/LookoutEyepatch.png'),
('Lookout',
'Steal a treasure and move it in front of you.',
'J', 0, 2, false, false, false, false, false, '/resources/static/images/cards/LookoutSkull.png'),
('Lookout',
'Steal a treasure and move it in front of you.',
'J', 0, 3, false, false, false, false, false, '/resources/static/images/cards/LookoutHook.png'),
('First Mate',
'Your treasures are protected. They cannot be destroyed or stolen.',
'Q', 1, 1, false, false, false, false, false, '/resources/static/images/cards/FirstMateEyepatch.png'),
('First Mate',
'Your treasures are protected. They cannot be destroyed or stolen.',
'Q', 1, 2, false, false, false, false, false, '/resources/static/images/cards/FirstMateSkull.png'),
('First Mate',
'Your treasures are protected. They cannot be destroyed or stolen.',
'Q', 1, 3, false, false, false, false, false, '/resources/static/images/cards/FirstMateHook.png'),
('Pirate King',
'Your treasures are worth 3 more doubloons each.',
'K', 1, 1, false, false, false, false, false, '/resources/static/images/cards/PirateKingEyepatch.png'),
('Pirate King',
'Your treasures are worth 3 more doubloons each.',
'K', 1, 2, false, false, false, false, false, '/resources/static/images/cards/PirateKingSkull.png'),
('Pirate King',
'Your treasures are worth 3 more doubloons each.',
'K', 1, 3, false, false, false, false, false, '/resources/static/images/cards/PirateKingHook.png');

INSERT INTO games(round, turn, num_players, host, mode, time, is_active) VALUES
(2, 'player5', 4, 'player2', 0, 3, false),
(3, 'Robot Pirate', 1, 'player4', 1, 5, false),
(1, 'player3', 3, 'player1', 2, 4, false);

INSERT INTO games_players(game_id, players_id) VALUES
(1, 2),
(1, 3),
(1, 4),
(1, 5),
(2, 4),
(3, 3),
(3, 4),
(3, 5);

INSERT INTO players_friends(player_id, friends_id) VALUES
(2, 3),
(2, 4),
(2, 5),
(3, 2),
(3, 4),
(3, 5),
(4, 2),
(4, 3),
(4, 5),
(5, 2),
(5, 3),
(5, 4);